language: rust
sudo: false
cache: cargo
dist: trusty

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

rust:
  - stable
  - beta
  - nightly

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH
  - cargo install cargo-travis --force && export PATH=$HOME/.cargo/bin:$PATH;

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only stable doc

# Inspired from geal/nom
after_success:
  - if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" != "master" ] && [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      cargo install cargo-benchcmp --force;
      cargo bench > benches-variable;
      git fetch;
      git checkout master;
      cargo bench > benches-control;
      cargo benchcmp benches-control benches-variable;
    fi
  - cargo coveralls --verbose;

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
