language: rust
rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

# Inspired from geal/nom
after_success:
  - if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" != "master" ] && [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo install cargo-benchcmp --force;
        cargo bench > benches-variable;
        git fetch;
        git checkout master;
        cargo bench > benches-control;
        cargo benchcmp benches-control benches-variable;
    fi
