[package]
name = "nom_locate"
version = "0.1.0"
authors = ["Florent FAYOLLE <florent.fayolle69@gmail.com>"]
license = "MIT"
description = "A special input type for nom to locate tokens"

documentation = "https://docs.rs/nom_locate/"
homepage = "https://github.com/fflorent/nom_locate"
repository = "https://github.com/fflorent/nom_locate"
readme = "README.md"

keywords = ["nom"]
categories = ["parsing"]

[badges]
travis-ci = { repository = "fflorent/nom_locate" }


[dependencies]
nom = "^3.1"
memchr = "1.0.1"

